name = "CommonSubexpressions"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
authors = ["Robin Deits <robin.deits@gmail.com>"]
version = "0.2.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "0.7, 1"
